name: Sync to S3
on:
  push:
    branches:
      - main
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          MIRROR_TARGET: projects
          SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          STORAGE_SERVICE_URL: https://gateway.storjshare.io
        with:
          args: --overwrite --remove